import AppKit

/// Raw pasteboard type identifiers Nori cares about.
///
/// Kept as plain strings so the capture pipeline can be tested without AppKit objects.
enum PasteboardType {
    static let utf8PlainText = NSPasteboard.PasteboardType.string.rawValue     // public.utf8-plain-text
    static let rtf = NSPasteboard.PasteboardType.rtf.rawValue                  // public.rtf
    static let html = NSPasteboard.PasteboardType.html.rawValue                // public.html
    static let png = NSPasteboard.PasteboardType.png.rawValue                  // public.png
    static let tiff = NSPasteboard.PasteboardType.tiff.rawValue                // public.tiff
    static let jpeg = "public.jpeg"
    static let heic = "public.heic"
    static let fileURL = NSPasteboard.PasteboardType.fileURL.rawValue          // public.file-url
    static let url = NSPasteboard.PasteboardType.URL.rawValue                  // public.url
    static let pdf = NSPasteboard.PasteboardType.pdf.rawValue

    /// Written by Nori when it puts an item back on the pasteboard. The payload is the item UUID.
    static let noriItem = "io.github.hocky0301.Nori.item"

    /// http://nspasteboard.org conventions honoured by password managers and clipboard tools.
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    static let source = "org.nspasteboard.source"

    /// Set by macOS when the content arrived through Universal Clipboard (Handoff).
    static let universalClipboard = "com.apple.is-remote-clipboard"

    /// Types that describe *this* copy rather than the content; never stored, never hashed.
    static let metadataTypes: Set<String> = [
        noriItem,
        source,
        universalClipboard,
        "x.nspasteboard.ModifiedType",
        "com.apple.linkpresentation.metadata",
        "com.apple.WebKit.custom-pasteboard-data",
        "org.chromium.web-custom-data",
        "org.chromium.source-url",
        "org.chromium.internal.source-rfh-token",
        "com.apple.notes.richtext",
    ]

    /// A concealed copy leaves a ghost row; transient / auto-generated copies are ignored silently.
    static let ephemeralTypes: Set<String> = [transient, autoGenerated]

    /// Custom types used by password managers and snippet tools. Skipped by default; user-editable.
    static let defaultIgnoredTypes: [String] = [
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.apple.pasteboard.promised-file-url",
    ]

    /// Password managers whose copies are never recorded by default.
    static let defaultIgnoredApps: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.dashlane.Dashlane",
    ]

    static let imageTypes: [String] = [png, tiff, jpeg, heic]
    static let textTypes: [String] = [utf8PlainText, rtf, html]

    /// Representations that participate in duplicate detection.
    static let stableTypes: Set<String> = Set(imageTypes + textTypes + [fileURL])

    /// Prefixes of per-process dynamic types that are meaningless after the copying app quits.
    static let ignoredPrefixes: [String] = ["dyn.", "com.microsoft.ole.source."]

    /// Microsoft Word bookmark/cross-reference types that make Word paste a link instead of text.
    static let microsoftLinkTypes: Set<String> = ["com.microsoft.ObjectLink", "com.microsoft.Link-Source"]
}
